language: node_js
node_js:
  - '6.1'
  - '6.0'
services:
  -mysql
before_script:
  - mysql -e "create database IF NOT EXISTS lta;" -uroot
script:
  - npm run test:integration
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"


